-- Add universal_research_output column to research_reports table
ALTER TABLE research_reports 
ADD COLUMN IF NOT EXISTS universal_research_output TEXT;

-- Add comment to column
COMMENT ON COLUMN research_reports.universal_research_output IS 'Universal Research Framework output generated by Claude';

